[Logging]
LogLevel=LOG_DEBUG
MaxRotateFiles=10
MaxFileSizeInMB=10
DailyRotate=1
ShowEventType=1
ShowHeaderInfo=1
Enabled=1
TimePrecission=1

[Connection]
AccessKey=
AccessKeyName=saspolicy
Namespace=yournamespace.servicebus.windows.net
HybridConnection=yourhybridconnection

[Adapters]
; Folder (relative to the executable or absolute) that contains adapter
; shared libraries (vc-adapter-*.dll / .so / .dylib)
Directory=.
